DELETE  http://localhost:3001/api/persons/2 

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "",
    "number":null
}

###
GET http://localhost:3001/api/persons/


###
GET http://localhost:3001/api/persons/60a4838721a83c58a0b9196c
